/* Generated By:JJTree: Do not edit this line. ASTClassDecl.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.example;

import java.util.ArrayList;
import java.util.List;

public
class ASTClassDecl extends SimpleNode {
    String name;
    String parent;

    List<ASTVarDecl> fields = new ArrayList<>();
    List<ASTMethodDecl> methods = new ArrayList<>();

    public ASTClassDecl(int id) {
        super(id);
    }

    public ASTClassDecl(MiniJavaParser p, int id) {
        super(p, id);
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setParent(String parent) {
        this.parent = parent;
    }

    public void addField(ASTVarDecl local) {
        fields.add(local);
    }

    public void addMethod(ASTMethodDecl local) {
        methods.add(local);
    }

    /**
     * Accept the visitor.
     **/
    public Object jjtAccept(MiniJavaParserVisitor visitor, Object data) {

        return
                visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=8aad99ae12b96b2d98d70f9d08cc8507 (do not edit this line) */
