/* Generated By:JJTree: Do not edit this line. ASTExpLog.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.example;

public
class ASTExpLog extends SimpleNode {

  ASTExpRel rel;
  ASTExpLog2 log;

  public ASTExpLog(int id) {
    super(id);
  }

  public ASTExpLog(MiniJavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0ccac73b688560ed8f076395f1572c24 (do not edit this line) */
