/* Generated By:JJTree: Do not edit this line. ASTExpRel.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.example;

public
class ASTExpRel extends SimpleNode {
  ASTCondition cond;
  ASTExpArm expArm;
  ASTExpArm expArm2;

  public ASTExpRel(int id) {
    super(id);
  }

  public ASTExpRel(MiniJavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=233fb64d16e5e84677aea942950fe3f4 (do not edit this line) */
