/* Generated By:JJTree: Do not edit this line. ASTExpTerm.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.example;

public
class ASTExpTerm extends SimpleNode {
  ASTExpFact fact;
  ASTExpTerm2 term;
  public ASTExpTerm(int id) {
    super(id);
  }

  public ASTExpTerm(MiniJavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7c85e7e482c2424c56055bf1a6024f7a (do not edit this line) */
