/* Generated By:JJTree: Do not edit this line. ASTLogExpTerm.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.example;

public
class ASTLogExpTerm extends SimpleNode {
  public ASTLogExpTerm(int id) {
    super(id);
  }

  public ASTLogExpTerm(MiniJavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cbefee9b9dc721ce54e862a25842c144 (do not edit this line) */
