/* Generated By:JJTree: Do not edit this line. ASTMainClass.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.example;

import java.util.ArrayList;
import java.util.List;

public
class ASTMainClass extends SimpleNode {
  String name;
  List<ASTVarDecl> locals = new ArrayList<>();
  public ASTMainClass(int id) {
    super(id);
  }

  public ASTMainClass(MiniJavaParser p, int id) {
    super(p, id);
  }

  public void setName(String name) {
    this.name = name;
  }

  public void locals(ASTVarDecl local) {
    locals.add(local);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f59c7653e3f22568777cb4137fd4660a (do not edit this line) */
