/* Generated By:JJTree: Do not edit this line. ASTMethodDecl.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.example;

import java.util.ArrayList;
import java.util.List;

public
class ASTMethodDecl extends SimpleNode {
    ASTType returnType;
    String name;
    List<String> paramTypes = new ArrayList<>();
    List<String> paramNames = new ArrayList<>();
    List<ASTVarDecl> locals = new ArrayList<>();

    public ASTMethodDecl(int id) {
        super(id);
    }

    public ASTMethodDecl(MiniJavaParser p, int id) {
        super(p, id);
    }

    public void setReturnType(ASTType returnType) {
        this.returnType = returnType;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void addParamType(String paramType) {
        paramTypes.add(paramType);
    }

    public void addParamName(String paramName) {
        paramNames.add(paramName);
    }

    public void addLocal(ASTVarDecl local) {
        locals.add(local);
    }

    /**
     * Accept the visitor.
     **/
    public Object jjtAccept(MiniJavaParserVisitor visitor, Object data) {

        return
                visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=762849606564d44291bbf64f32112dfe (do not edit this line) */
