/* Generated By:JJTree: Do not edit this line. ASTVarDecl.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.example;

public
class ASTVarDecl extends SimpleNode {
  String name;
  ASTType typeNode;
  public ASTVarDecl(int id) {
    super(id);
  }

  public ASTVarDecl(MiniJavaParser p, int id) {
    super(p, id);
  }

  public void setName(String name) {
    this.name = name;
  }

  public void setTypeNode(ASTType typeNode) {
    this.typeNode = typeNode;
  }

  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7978be06cb8854f4e26ac24dc2e2e6f4 (do not edit this line) */
