/* Generated By:JavaCC: Do not edit this line. MiniJavaParserVisitor.java Version 7.0.13 */
package org.example;

public interface MiniJavaParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTMainClass node, Object data);
  public Object visit(ASTClassDecl node, Object data);
  public Object visit(ASTVarDecl node, Object data);
  public Object visit(ASTMethodDecl node, Object data);
  public Object visit(ASTType node, Object data);
}
/* JavaCC - OriginalChecksum=c46c3b71572f339c87abb914cb85e1c7 (do not edit this line) */
