/* Generated By:JavaCC: Do not edit this line. MiniJavaParserTreeConstants.java Version 7.0.13 */
package org.example;

public interface MiniJavaParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTMAINCLASS = 1;
  public int JJTCLASSDECL = 2;
  public int JJTVARDECL = 3;
  public int JJTMETHODDECL = 4;
  public int JJTFORMALLIST = 5;
  public int JJTFORMALREST = 6;
  public int JJTTYPE = 7;
  public int JJTSTATEMENT = 8;
  public int JJTEXP = 9;
  public int JJTCONDITION = 10;
  public int JJTEXPLOG = 11;
  public int JJTEXPLOG2 = 12;
  public int JJTOPLOG = 13;
  public int JJTEXPREL = 14;
  public int JJTOPREL = 15;
  public int JJTEXPARM = 16;
  public int JJTEXPARM2 = 17;
  public int JJTOPAD = 18;
  public int JJTEXPTERM = 19;
  public int JJTEXPTERM2 = 20;
  public int JJTOPMUL = 21;
  public int JJTEXPFACT = 22;
  public int JJTACCESS = 23;
  public int JJTCALL = 24;
  public int JJTCALL2 = 25;
  public int JJTCALLTARGET = 26;
  public int JJTEXPLIST = 27;
  public int JJTEXPREST = 28;


  public String[] jjtNodeName = {
    "Program",
    "MainClass",
    "ClassDecl",
    "VarDecl",
    "MethodDecl",
    "FormalList",
    "FormalRest",
    "Type",
    "Statement",
    "Exp",
    "Condition",
    "ExpLog",
    "ExpLog2",
    "OpLog",
    "ExpRel",
    "OpRel",
    "ExpArm",
    "ExpArm2",
    "OpAd",
    "ExpTerm",
    "ExpTerm2",
    "OpMul",
    "ExpFact",
    "Access",
    "Call",
    "Call2",
    "CallTarget",
    "ExpList",
    "ExpRest",
  };
}
/* JavaCC - OriginalChecksum=4c3f0c62ee93829d724f72c98fd4e1d6 (do not edit this line) */
