/* Generated By:JavaCC: Do not edit this line. MiniJavaParserTreeConstants.java Version 7.0.13 */
package org.example;

public interface MiniJavaParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTMAINCLASS = 1;
  public int JJTCLASSDECL = 2;
  public int JJTVARDECL = 3;
  public int JJTMETHODDECL = 4;
  public int JJTVOID = 5;
  public int JJTTYPE = 6;


  public String[] jjtNodeName = {
    "Program",
    "MainClass",
    "ClassDecl",
    "VarDecl",
    "MethodDecl",
    "void",
    "Type",
  };
}
/* JavaCC - OriginalChecksum=f1d097934c2819b482d8541eaee53b02 (do not edit this line) */
