/* Generated By:JavaCC: Do not edit this line. MiniJavaParserDefaultVisitor.java Version 7.0.13 */
package org.example;

public class MiniJavaParserDefaultVisitor implements MiniJavaParserVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTProgram node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMainClass node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTClassDecl node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTVarDecl node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMethodDecl node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFormalList node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFormalRest node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTType node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTStatement node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTExp node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCondition node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLogExp node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLogExpTerm node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLogExpFactor node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTRelExp node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTRelOp node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTArExp node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAddOp node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTTerm node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMulOp node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFactor node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=98041e5a3f69086a52509394845b4767 (do not edit this line) */
